--Consultas Avanzadas en Oracle
--1. Definición
--Las consultas avanzadas en Oracle son sentencias SQL que permiten trabajar con una o más tablas, realizando operaciones complejas como combinaciones (JOIN), subconsultas, agrupaciones, funciones analíticas y operadores de conjunto.
--2. Tipos de Consultas Avanzadas
--a) JOINs Avanzados Permiten relacionar dos o más tablas según claves compartidas.
--Ejemplo (INNER JOIN):
SELECT EMPLEADO.NOM_EMP AS EMPLEADO, EMPLEADO.APE_EMP AS APELLIDO, COMUNA.NOM_COM AS COMUNA
FROM EMPLEADO
INNER JOIN COMUNA
ON EMPLEADO.COMUNA_COD_COM = COMUNA.COD_COM
ORDER BY APELLIDO ASC;

--Ejemplo (LEFT JOIN):
SELECT EMPLEADO.NOM_EMP AS EMPLEADO, COMUNA.NOM_COM ASCOMUNA
FROM EMPLEADO
LEFT JOIN COMUNA
ON EMPLEADO.COMUNA_COD_COM = COMUNA.COD_COM
ORDER BY COMUNA ASC;

--Ejemplo (RIGHT JOIN):
SELECT EMPLEADO.NOM_EMP AS EMPLEADO, COMUNA.NOM_COM AS COMUNA
FROM EMPLEADO
RIGHT JOIN COMUNA
ON EMPLEADO.COMUNA_COD_COM = COMUNA.COD_COM
ORDER BY COMUNA ASC;

--b) Subconsultas (Subqueries) Consultas dentro de otras para obtener resultados intermedios.
SELECT EMPLEADO.NOM_EMP, EMPLEADO.SUELD_EMP
FROM EMPLEADO
WHERE EMPLEADO.SUELD_EMP>(SELECT AVG(SUELD_EMP) FROM EMPLEADO);

--LISTA A TODOS LOS EMPLEADOS CUYO SUELDO ES MAYOR QUE EL PROMEDIO DE SUELDOS DE LOS EMPLEADOS----
SELECT EMPLEADO.NOM_EMP, EMPLEADO.SUELD_EMP
FROM EMPLEADO
WHERE EMPLEADO.SUELD_EMP<(SELECT AVG(SUELD_EMP) FROM EMPLEADO);

--LISTA A TODOS LOS EMPLEADOS CUYO SUELDO ES MENOR QUE EL PROMEDIO DE SUELDOS DE LOS EMPLEADOS----
--c) Funciones de Agregación y GROUP BY - Se usan para resumir información.
SELECT CARGO.NOM_CARGO, SUM(SUELD_EMP) AS TOTAL_SALARIO
FROM EMPLEADO
JOIN CARGO
ON EMPLEADO.CARGO_ID_CARGO = CARGO.ID_CARGO
GROUP BY CARGO.NOM_CARGO;

--ESTA CONSULTA LISTA TOTAL SUELDO, AGRUPADOS POR CARGO---Ejemplo con HAVING:
SELECT CARGO.NOM_CARGO, SUM(SUELD_EMP) AS TOTAL_SALARIO
FROM EMPLEADO
JOIN CARGO
ON EMPLEADO.CARGO_ID_CARGO = CARGO.ID_CARGO
GROUP BY CARGO.NOM_CARGO
HAVING SUM(EMPLEADO.SUELD_EMP) > 2000000;

--ESTA CONSULTA LISTA TOTAL SUELDO, AGRUPADOS POR CARGO,PERO SOLO AQUELLOS MAYORES DE 2000000---
--d) Funciones Analíticas (OVER, RANK, ROW_NUMBER)
--Permiten cálculos avanzados sin agrupar.
SELECT EMPLEADO.NOM_EMP AS EMPLEADO, APE_EMP AS APELLIDO,
SUELD_EMP AS SALARIO,
RANK() OVER (ORDER BY SUELD_EMP DESC) AS RANKING
FROM EMPLEADO
  
---LISTA EMPLEADO, APELLIDO Y SALARIO EN UN RANKING DE SUELDOS DESENDENTE---
SELECT EMPLEADO.NOM_EMP AS EMPLEADO, APE_EMP AS APELLIDO,
SUELD_EMP AS SALARIO,
RANK() OVER (ORDER BY SUELD_EMP ASC) AS RANKING
FROM EMPLEADO
  
---LISTA EMPLEADO, APELLIDO Y SALARIO EN UN RANKING DE SUELDOS ASCENDENTE---
--e) Operadores de Conjunto (UNION) Combinan resultados de varias consultas.
SELECT empleado.NOM_EMP AS nombre_dato
FROM empleado
UNION ALL
SELECT comuna.NOM_COM
FROM comuna;
---ESTO DEVUELVE TODOS LOS NOMBRES (EMPLEADO Y COMUNAS) EN UNA SOLA LISTA
--SI DESEAS QUE APAREZCAN LOS DUPLICADOS USA UNION ALL.
SELECT ID_EMP FROM EMPLEADO
UNION ALL
SELECT ID_DPTO FROM DEPARTAMENTO;
--IDEM 
